# Generated by Django 4.2.11 on 2024-03-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
