# Generated by Django 4.2.11 on 2024-03-10 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_empresa_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='profissional',
            name='especialidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicos'),
        ),
    ]
