# Generated by Django 4.2.11 on 2024-03-12 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_servicos_alter_profissional_especialidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicos',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='servico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
