# Generated by Django 4.2.11 on 2024-03-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_servicos_empresa_alter_servicos_servico'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_abertura', models.TimeField()),
                ('duracao_minutos', models.IntegerField()),
            ],
        ),
    ]
