# Generated by Django 4.2.11 on 2024-03-13 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_profissional_imagem_alter_servicos_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='horarioatendimento',
            name='profissional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.profissional'),
        ),
        migrations.AddField(
            model_name='horarioatendimento',
            name='servicos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.servicos'),
        ),
    ]
