# Generated by Django 4.2.11 on 2024-03-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_horarioatendimento_profissional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horarioatendimento',
            name='confirmacao',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horarioatendimento',
            name='duracao_minutos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horarioatendimento',
            name='hora_abertura',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
