# Generated by Django 4.2.11 on 2024-03-13 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_horarioatendimento_confirmacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horarioatendimento',
            name='servicos',
        ),
    ]
