# Generated by Django 4.2.11 on 2024-03-13 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_confirmacaoagendamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmacaoagendamento',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
    ]
