# Generated by Django 4.2.11 on 2024-03-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_confirmacaoagendamento_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/'),
        ),
    ]
