# Generated by Django 4.2.11 on 2024-03-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_empresa_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicos',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
